version: "3.9"

services:
  web-dev:
    build:
      context: ./app
      dockerfile: dev.Dockerfile
    ports:
      - 3333:3000
    env_file:
      - ./.env.dev
    volumes:
      - ./app:/app
      - ./uploads:/app/uploads
    depends_on:
      - db
    profiles:
      - dev
    networks:
      - rede_local

  web-prod:
    build:
      context: ./app
      dockerfile: prod.Dockerfile
    ports:
      - 6998:3000
    env_file:
      - ./.env.prod
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
    profiles:
      - prod
    networks:
      - rede_local

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: developer  
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: gopload
    ports:
      - 6697:5432
    volumes:
      - gopgdata:/var/lib/postgresql/data
    networks:
      - rede_local
  
networks:
  rede_local:
    driver: bridge

volumes:
  gopgdata:
